name: Android CI

env:
  # The name of the main module repository
  main_project_module: Social Spark

  # The name of the Play Store
  playstore_name: IIECat
  
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Accept Android SDK licenses
      run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses

    - name: Build with Gradle
      run: ./gradlew build

    - name: Run tests
      run: ./gradlew test
